import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Car Doctor Next",
  description: "Generated by create next app and built by Allsamir",
  kewords: ["app", "web development", "website", "car", "doctor", "sevices"],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="shortcut icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ7WS-bBWfYKYOJmPCiqg9nZX4qXyyvhINr_A&s"
          type="image/x-icon"
        />
      </head>
      <body className={inter.className}>
        <div className="container mx-auto md:px-4">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
